server:
  port: 8002

spring:
  profiles:
    active: prod
  application:
    name: shortlink-admin
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config.yaml
    hikari:
      connection-test-query: select 1
      connection-timeout: 20000
      idle-timeout: 300000
      maximum-pool-size: 5
      minimum-idle: 5
  data:
    redis:
      host: ${app.redis.host}
      port: ${app.redis.port:6379}
      password: ${app.redis.password}
      database: ${app.redis.database:2}
  web:
    resources:
      add-mappings: false # 禁止默认的静态资源映射
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 500MB

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml  #指定sql映射文件
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名

springdoc:
  # 默认展开参数
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: cn.luowb.shortlink.admin

sa-token:
  token-name: token
  # 关闭同一账号并发登录
  is-concurrent: false
  # 顶人下线的范围（ALL_DEVICE_TYPE 表示所有设备端统统互斥）
  replaced-range: ALL_DEVICE_TYPE
  # 新旧设备冲突时的退出模式（OLD_DEVICE=旧设备下线，新设备成功；NEW_DEVICE=新设备登录失败，旧设备保持在线）
  replaced-login-exit-mode: OLD_DEVICE

app:
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:}
    database: ${REDIS_DATABASE:2}
  group:
    max-count: 20
